# Generated by Django 5.2.3 on 2025-06-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commentaire_personnes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='personnes',
            new_name='personne',
        ),
    ]
