# Generated by Django 5.2.3 on 2025-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_personnes_commentaire_personne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=75)),
                ('annee', models.DateField()),
                ('realisateur', models.CharField(max_length=75)),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
