# Generated by Django 5.2.3 on 2025-06-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='film',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.film'),
        ),
    ]
