# Generated by Django 5.2.3 on 2025-06-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_commentaire_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='acteurs/')),
            ],
        ),
        migrations.CreateModel(
            name='CategorieFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('descriptif', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acteur')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.film')),
            ],
        ),
    ]
