# Generated by Django 5.2.3 on 2025-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_acteur_categoriefilm_casting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CategorieFilm',
        ),
        migrations.AlterField(
            model_name='acteur',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='nom',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='prenom',
            field=models.CharField(max_length=75),
        ),
    ]
