# Generated by Django 5.2.3 on 2025-06-17 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_categorie_delete_categoriefilm_alter_acteur_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='acteur',
            field=models.ManyToManyField(related_name='film', to='app.acteur'),
        ),
        migrations.AddField(
            model_name='film',
            name='categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.categorie'),
        ),
    ]
