# Generated by Django 5.2.3 on 2025-06-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_film_acteur_film_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('descriptif', models.TextField(max_length=255)),
            ],
        ),
    ]
